name: All Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    uses: ./.github/workflows/test-backend.yml
  
  frontend:
    uses: ./.github/workflows/test-frontend.yml
  
  e2e:
    uses: ./.github/workflows/test-e2e.yml
    needs: [backend, frontend]
  
  mobile:
    uses: ./.github/workflows/test-mobile.yml
    needs: [backend, frontend]
  
  security:
    uses: ./.github/workflows/test-security.yml
  
  performance:
    uses: ./.github/workflows/test-performance.yml
    needs: [backend, frontend]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

  report:
    runs-on: ubuntu-latest
    needs: [backend, frontend, e2e, mobile, security]
    if: always()
    
    steps:
      - name: Generate test summary
        run: |
          echo "## Test Suite Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Backend Tests: ${{ needs.backend.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Frontend Tests: ${{ needs.frontend.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ E2E Tests: ${{ needs.e2e.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Mobile Tests: ${{ needs.mobile.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Security Tests: ${{ needs.security.result }}" >> $GITHUB_STEP_SUMMARY
      
      - name: Check if all tests passed
        if: |
          needs.backend.result != 'success' ||
          needs.frontend.result != 'success' ||
          needs.e2e.result != 'success' ||
          needs.mobile.result != 'success' ||
          needs.security.result != 'success'
        run: |
          echo "Some tests failed!"
          exit 1
